server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        return 302 /sehomework/;
    }

    location /sehomework/ {
        try_files $uri $uri/ /sehomework/index.html;
    }

    error_page 404 /sehomework/404.html;
}
